### PR TITLE
Remove skid and some unnecessary things.

### PR DESCRIPTION
**Pull request by Milxnor**
It's lawinserver the skided part btw just look at the source bruh

### CODE REVIEW

**Comment by AlexDev404** [comment]
Some parts of your code contain removals that are not necessary. Due to this I will be marking your pull request (#27) as invalid. I suggest you make a new pull request.

**Comment by AlexDev404** [comment]
I will still be looking into this though

**Comment by AlexDev404** [comment]
Will be closing pull #27 in **24 hours** after last reply.

**Comment by Milxnor** [comment]
you are a potato

**Pull request closed without merging**
